#
# Make sure temp directories used by install is always available
#

- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory

- name: get PATH
  shell: echo $PATH
  register: path

- name: download kubectl
  include: kubectl.yml

#
# Deploys Jupyter Enterprise Gateway and download kernel images
- name: download enterprise gateway yaml file, replace image tag and deploy enterprise-gateway
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  block:
    - get_url:
        url: https://raw.githubusercontent.com/jupyter-incubator/enterprise_gateway/{{ jupyter_enterprise_gateway.version }}/etc/kubernetes/enterprise-gateway.yaml
        dest: "{{ install_temp_dir }}/enterprise-gateway.yaml"
    - replace:
        path: "{{ install_temp_dir }}/enterprise-gateway.yaml"
        regexp: 'image: elyra/enterprise-gateway:dev'
        replace: 'image: lresende/enterprise-gateway:dev'
    - shell: |
        kubectl apply -f "{{ install_temp_dir }}/enterprise-gateway.yaml"

- name: Ingress configuration for Enterprise Gateway
  template:
    src: enterprise-gateway-ingress.yaml.j2
    dest: "{{ install_temp_dir }}/enterprise-gateway-ingress.yaml"
    mode: 0644

- name: Apply ingress configuration for Enterprise Gateway
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
     kubectl apply -f {{ install_temp_dir }}/enterprise-gateway-ingress.yaml
